source "http://rubygems.org"

gem "capybara",           "3.18.0" 
gem "cucumber",           "3.1.2"
gem "rspec",              "3.9.0"
gem "selenium-webdriver", "3.142.7"
gem "site_prism",         "3.4" 
gem "pry"
gem "os",                 "1.0.1"
gem "pg",                 "1.1.4"
gem "report_builder"
gem "ffi"
gem "rubocop"
